apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: weixu
spec:
  acme:
    # Production Let's Encrypt server
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email for Let's Encrypt notifications
    email: weixu@iiis.co
    # Secret to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    # DNS-01 challenge solver using Cloudflare
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: api-token
